import Link from "next/link";
import { ArrowLeft } from "lucide-react";
import { Nav } from "@/components/nav";
import { Footer } from "@/components/footer";

export default function TermsPage() {
  return (
    <div className="min-h-screen bg-parchment">
      <Nav />
      <section className="pt-28 pb-20 sm:pt-36">
        <div className="max-w-2xl mx-auto px-4 sm:px-6 lg:px-8">
          <Link
            href="/"
            className="inline-flex items-center gap-2 text-sm text-weathered hover:text-bark transition-colors mb-10"
          >
            <ArrowLeft className="w-4 h-4" />
            Back to home
          </Link>
          <h1
            className="text-4xl font-bold text-bark mb-3"
            style={{ fontFamily: "var(--font-fraunces)" }}
          >
            Terms of Service
          </h1>
          <p className="text-sm text-weathered mb-12">
            Last updated: March 2026
          </p>

          <div className="prose-crutan space-y-8">
            {[
              {
                title: "Acceptance of Terms",
                body: "By using Crutan, you agree to these Terms of Service. If you don't agree, please don't use the service. We may update these terms occasionally — we'll notify you of material changes via email.",
              },
              {
                title: "What Crutan Does",
                body: "Crutan connects to your Google Analytics 4 and Search Console accounts (with your permission) and generates AI-written analytics briefings. It is an informational tool — reports are for informational purposes only and should not be the sole basis for significant business decisions.",
              },
              {
                title: "Your Responsibilities",
                body: "You are responsible for ensuring you have the right to connect the GA4 properties you link to Crutan. You agree not to use Crutan to access data you are not authorized to view. You are responsible for keeping your account credentials secure.",
              },
              {
                title: "Acceptable Use",
                body: "You agree not to use Crutan to violate any applicable laws, access data without authorization, attempt to circumvent rate limits or usage restrictions, or reverse-engineer the service.",
              },
              {
                title: "Service Availability",
                body: "Crutan is provided as-is during early access. We do not guarantee uptime or uninterrupted service. We reserve the right to modify or discontinue any feature with reasonable notice.",
              },
              {
                title: "AI-Generated Content",
                body: "Reports and chat responses are generated by AI. They may contain errors or inaccuracies. Always verify significant findings against your actual data. Crutan is not liable for decisions made based on AI-generated content.",
              },
              {
                title: "Intellectual Property",
                body: "The Crutan platform, branding, and software are owned by Crutan. You retain ownership of your analytics data. You grant Crutan a limited license to process your data for the purpose of providing the service.",
              },
              {
                title: "Limitation of Liability",
                body: "To the maximum extent permitted by law, Crutan's liability for any claim arising from use of the service is limited to the amount you paid us in the 12 months preceding the claim. During free early access, this is $0.",
              },
              {
                title: "Contact",
                body: "Questions about these terms? Contact us at legal@crutan.com.",
              },
            ].map((section) => (
              <div key={section.title}>
                <h2
                  className="text-xl font-semibold text-bark mb-3"
                  style={{ fontFamily: "var(--font-fraunces)" }}
                >
                  {section.title}
                </h2>
                <p className="text-loam leading-relaxed text-sm">{section.body}</p>
              </div>
            ))}
          </div>
        </div>
      </section>
      <Footer />
    </div>
  );
}
